export const COMPANY__SET_COMPANIES = 'COMPANY__SET_COMPANIES';
export const COMPANY__UNSET_COMPANIES = 'COMPANY__UNSET_COMPANIES';
export const COMPANY__SET_CURRENT_COMPANY = 'COMPANY__SET_CURRENT_COMPANY';
export const COMPANY__UNSET_CURRENT_COMPANY = 'COMPANY__UNSET_CURRENT_COMPANY';